### ISSUE TITLE
I can't buy in Lords mobile

### ISSUE THREAD

**Issue by bamrieid** [Aptoide/appcoins-wallet-android#603]
I have appc in my wallet and I installed aptoide and updated Lord's mobile from aptoide but still can't buy with appc the option is not active. A screenshot of the payment options in Lord's mobile is attached
![Screenshot_20200201-083437](https://user-images.githubusercontent.com/43845133/73588144-f81f3280-44cd-11ea-9ebd-b88baae95cf5.png)
![447803261_345405](https://user-images.githubusercontent.com/43845133/73588190-c195e780-44ce-11ea-9ce5-349a040f1226.jpg)

**Comment by JoaoRaimundo** [comment]
hi @bamrieid,
The reason that stops you from buying items with AppCoins is probably because you don't have Ethereum to pay the payment fees.
AppCoins as an Ethereum token requires Ethereum to pay the transaction fees.
After you get ethereum on your wallet, please let us know if you were able to make the purchase.
